# -*- coding: utf-8 -*-
"""dash_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-bCRHCZJxbSVnGhoHxky4cFLliP_J5_E
"""

# !pip install dash

import dash
from dash import html, dcc
import pandas as pd

import plotly.express as px

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("stockdata.csv")

## creating the app
app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1('Time Series Dashboard'),
    dcc.Dropdown(
        id='company-dropdown',
        options=[{'label': i, 'value': i} for i in df['Company'].unique()],
        value='IBM'
    ),
    dcc.Graph(id='open-graph'),
    dcc.Graph(id='high-graph'),
    dcc.Graph(id='low-graph'),
    dcc.Graph(id='close-graph'),
    dcc.Graph(id='volume-graph')
])

## creating callback to connect graphs with Dash
@app.callback(
    [dash.dependencies.Output('open-graph', 'figure'),
     dash.dependencies.Output('high-graph', 'figure'),
     dash.dependencies.Output('low-graph', 'figure'),
     dash.dependencies.Output('close-graph', 'figure'),
     dash.dependencies.Output('volume-graph', 'figure')],
    [dash.dependencies.Input('company-dropdown', 'value')])

def update_graph(company):
    company_df = df[df['Company'] == company]

    open_fig = px.line(company_df, x='Date', y='Open')
    high_fig = px.line(company_df, x='Date', y='High')
    low_fig = px.line(company_df, x='Date', y='Low')
    close_fig = px.line(company_df, x='Date', y='Close')
    volume_fig = px.line(company_df, x='Date', y='Volume')

    return open_fig, high_fig, low_fig, close_fig, volume_fig

if __name__ == '__main__':
    app.run_server(debug=True)

